/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#dfe3e7', 'primary-fixed-dim': '#d0c2d0', 'on-tertiary-container': '#a592ff',
        'inverse-surface': '#283044', 'surface-tint': '#655b67', 'inverse-on-surface': '#eef0ff',
        'primary-fixed': '#eddeed', 'tertiary-fixed-dim': '#cabeff', error: '#ba1a1a',
        'on-surface-variant': '#4a454a', 'on-secondary-fixed': '#171c1f', 'surface-container-high': '#e2e7ff',
        'outline-variant': '#ccc4ca', 'on-tertiary': '#ffffff', 'tertiary-fixed': '#e6deff',
        'on-primary-fixed': '#211923', surface: '#faf8ff', 'primary-container': '#3e3540',
        'inverse-primary': '#d0c2d0', 'surface-container-low': '#f2f3ff', 'on-surface': '#131b2e',
        background: '#faf8ff', 'on-primary-fixed-variant': '#4d444f', 'on-background': '#131b2e',
        'surface-container': '#eaedff', 'on-error': '#ffffff', 'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff', 'on-tertiary-fixed-variant': '#4918c8', secondary: '#5a5f62',
        outline: '#7c757b', 'surface-variant': '#dae2fd', 'secondary-fixed-dim': '#c3c7cb',
        'surface-container-highest': '#dae2fd', 'on-primary': '#ffffff', 'surface-bright': '#faf8ff',
        'on-secondary': '#ffffff', 'on-secondary-container': '#5e6367', 'secondary-container': '#dce0e4',
        primary: '#28202a', 'error-container': '#ffdad6', 'tertiary-container': '#3900ae', tertiary: '#230074',
        'on-tertiary-fixed': '#1c0062', 'on-primary-container': '#aa9dab', 'on-secondary-fixed-variant': '#43474b',
        'surface-dim': '#d2d9f4',
      },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '0.75rem' },
      spacing: {
        'space-xs': '0.25rem', 'space-sm': '0.5rem', 'margin-lg': '5rem', 'space-xl': '2.5rem',
        'margin-md': '3rem', margin: '1.5rem', 'space-md': '1rem', 'gutter-sm': '1rem', gutter: '1.5rem',
        'space-lg': '1.5rem', 'gutter-lg': '2rem',
      },
      fontFamily: {
        'label-lg': ['Plus Jakarta Sans'], 'body-md': ['Inter'], 'display-hero': ['Plus Jakarta Sans'],
        'body-sm': ['Inter'], 'headline-sm': ['Plus Jakarta Sans'], 'headline-lg-mobile': ['Plus Jakarta Sans'],
        'display-hero-mobile': ['Plus Jakarta Sans'], 'headline-md': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'], 'label-technical': ['Inter'], 'body-lg': ['Inter'],
        'label-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-hero': ['64px', { lineHeight: '72px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-hero-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-technical': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
